CREATE TABLE IF NOT EXISTS tenant (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  name VARCHAR(128) NOT NULL COMMENT '租户名称',
  code VARCHAR(64) NOT NULL COMMENT '租户编码',
  enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT NULL COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT NULL COMMENT '更新人',
  UNIQUE KEY uk_tenant_code (code)
) COMMENT='租户表';

CREATE TABLE IF NOT EXISTS org_unit (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  parent_id BIGINT NULL COMMENT '父节点ID',
  path VARCHAR(512) NOT NULL COMMENT '路径(/1/3/8/)',
  name VARCHAR(128) NOT NULL COMMENT '组织名称',
  type VARCHAR(32) NOT NULL COMMENT '组织类型',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT NULL COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT NULL COMMENT '更新人',
  KEY idx_org_unit_tenant_parent (tenant_id, parent_id)
) COMMENT='组织架构表';

CREATE TABLE IF NOT EXISTS `user` (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  external_sub VARCHAR(128) NULL COMMENT '外部身份标识(JWT sub)',
  login_name VARCHAR(64) NOT NULL COMMENT '登录名',
  password VARCHAR(255) NOT NULL COMMENT '密码哈希',
  username VARCHAR(64) NULL COMMENT '显示用户名',
  email VARCHAR(128) NULL COMMENT '邮箱',
  phone VARCHAR(32) NULL COMMENT '手机号',
  enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT NULL COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT NULL COMMENT '更新人',
  UNIQUE KEY uk_user_tenant_external_sub (tenant_id, external_sub),
  UNIQUE KEY uk_user_tenant_login_name (tenant_id, login_name)
) COMMENT='用户表';

CREATE TABLE IF NOT EXISTS user_org_unit (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  org_unit_id BIGINT NOT NULL COMMENT '组织ID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT NULL COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT NULL COMMENT '更新人'
) COMMENT='用户与组织关系表';

CREATE TABLE IF NOT EXISTS role (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  code VARCHAR(64) NOT NULL COMMENT '角色编码',
  name VARCHAR(128) NOT NULL COMMENT '角色名称',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT NULL COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT NULL COMMENT '更新人',
  UNIQUE KEY uk_role_tenant_code (tenant_id, code)
) COMMENT='角色表';

CREATE TABLE IF NOT EXISTS permission (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  action VARCHAR(128) NOT NULL COMMENT '权限动作',
  name VARCHAR(128) NOT NULL COMMENT '权限名称',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT NULL COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT NULL COMMENT '更新人',
  UNIQUE KEY uk_permission_tenant_action (tenant_id, action)
) COMMENT='权限表';

CREATE TABLE IF NOT EXISTS user_role (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  role_id BIGINT NOT NULL COMMENT '角色ID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT NULL COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT NULL COMMENT '更新人'
) COMMENT='用户与角色关系表';

CREATE TABLE IF NOT EXISTS role_permission (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  role_id BIGINT NOT NULL COMMENT '角色ID',
  permission_id BIGINT NOT NULL COMMENT '权限ID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT NULL COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT NULL COMMENT '更新人'
) COMMENT='角色与权限关系表';

CREATE TABLE IF NOT EXISTS infra_ping (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  msg VARCHAR(255) NOT NULL COMMENT '冒烟消息',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
) COMMENT='基础连通性冒烟表';

INSERT INTO infra_ping (msg, created_at)
VALUES ('pong', NOW());
